### ISSUE TITLE
didn't wirk in the latest firefox

### ISSUE THREAD

**Issue by ghost** [jeb5/YouTube-Subscriptions-RSS#1]
error looked like this:
<img width="1512" alt="Знімок екрана 2023-06-09 о 12 48 08" src="https://github.com/jeb5/YouTube-Subscriptions-RSS/assets/72412645/743178ab-2506-4a6e-80ec-fc8b9a332123">

**Comment by jeb5** [comment]
I've updated the code to fix a bug related to the query selector, so let me know if this fixes your issue.

Are you running the script at [https://www.youtube.com/feed/channels](https://www.youtube.com/feed/channels)?

Otherwise, try running `console.log([...document.querySelectorAll("ytd-browse:not([hidden]) #main-link.channel-link")].map(e=>e.href).join("\n"));` on the same page, and check if any of the links that show up don't end in `/@<username>`.
